import { afterAll, beforeEach, describe, expect, it, vi } from 'vitest';
import {
  AllProvidersRateLimitedError,
  generateReportNow,
  initializeProviders,
  registerCallbacks,
} from '../../src/stepper/orchestrator.js';
import { config } from '../../src/config.js';
import { RateLimitError } from '../../src/providers/provider.interface.js';
import { PromptInput, ReportOutput } from '../../src/types.js';

const mockHfProviderCall = vi.fn();
const mockUnifiedProviderCall = vi.fn();

vi.mock('../../src/providers/hfSpace.adapter.js', () => ({
  HuggingFaceSpaceAdapter: class {
    name = 'hf-space';

    async call(input: PromptInput) {
      return mockHfProviderCall(input);
    }
  },
}));

vi.mock('../../src/providers/unified.adapter.js', () => ({
  UnifiedProviderAdapter: class {
    name: string;

    constructor(spec: { name: string }) {
      this.name = spec.name;
    }

    async call(input: PromptInput) {
      return mockUnifiedProviderCall(this.name, input);
    }
  },
}));

const testInput: PromptInput = {
  userId: 'test-user',
  commitSha: 'abc123',
  repo: 'test/repo',
  message: 'Test commit',
  files: ['test.ts'],
  components: ['test'],
  diffSummary: '+ added test',
};

const mockReport: ReportOutput = {
  title: 'Test Report',
  summary: 'Generated by provider',
  changes: ['Change 1'],
  rationale: 'Test rationale',
  impact_and_tests: 'Test impact',
  next_steps: ['Next step'],
  tags: 'test',
};

const originalRetryConfig = { ...config.retry };

describe('Orchestrator rate-limit strategy', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    config.retry.maxAttemptsPerProvider = 2;
    config.retry.rateLimitFallbackSeconds = 1;
    config.retry.rateLimitStrategy = 'fallback';
  });

  afterAll(() => {
    config.retry.maxAttemptsPerProvider = originalRetryConfig.maxAttemptsPerProvider;
    config.retry.baseDelayMs = originalRetryConfig.baseDelayMs;
    config.retry.maxJitterMs = originalRetryConfig.maxJitterMs;
    config.retry.rateLimitFallbackSeconds = originalRetryConfig.rateLimitFallbackSeconds;
    config.retry.rateLimitStrategy = originalRetryConfig.rateLimitStrategy;
  });

  it('falls through to next provider immediately when strategy is fallback', async () => {
    initializeProviders([
      {
        name: 'hf-space',
        enabled: true,
        baseUrl: 'http://test.local',
        rateLimitRPS: 10,
        concurrency: 1,
        timeout: 5000,
      },
      {
        name: 'openai',
        enabled: true,
        modelName: 'gpt-4o-mini',
        apiKey: 'test-key',
        rateLimitRPS: 10,
        concurrency: 1,
        timeout: 5000,
      },
    ]);

    mockHfProviderCall.mockRejectedValueOnce(new RateLimitError('HF busy', 0.01));
    mockUnifiedProviderCall.mockResolvedValueOnce(mockReport);

    const start = Date.now();
    const result = await generateReportNow(testInput, 'fallback-strategy-job');
    const elapsed = Date.now() - start;

    expect(result.usedProvider).toBe('openai');
    expect(result.fallback).toBe(false);
    expect(mockHfProviderCall).toHaveBeenCalledTimes(1);
    expect(mockUnifiedProviderCall).toHaveBeenCalledTimes(1);
    expect(result.providersAttempted[0].errorCode).toBe('RATE_LIMIT');
    expect(result.providersAttempted[0].retryAfterSeconds).toBe(0.01);
    expect(elapsed).toBeLessThan(500);
  });

  it('retries the same provider inline when strategy is wait', async () => {
    config.retry.rateLimitStrategy = 'wait';

    initializeProviders([
      {
        name: 'hf-space',
        enabled: true,
        baseUrl: 'http://test.local',
        rateLimitRPS: 10,
        concurrency: 1,
        timeout: 5000,
      },
    ]);

    mockHfProviderCall
      .mockRejectedValueOnce(new RateLimitError('HF busy', 0.01))
      .mockResolvedValueOnce(mockReport);

    const result = await generateReportNow(testInput, 'wait-strategy-job');

    expect(result.usedProvider).toBe('hf-space');
    expect(result.fallback).toBe(false);
    expect(mockHfProviderCall).toHaveBeenCalledTimes(2);
  });

  it('throws a retryable all-providers-rate-limited error when every provider is rate-limited', async () => {
    const onFailure = vi.fn();
    registerCallbacks({ onFailure });

    initializeProviders([
      {
        name: 'hf-space',
        enabled: true,
        baseUrl: 'http://test.local',
        rateLimitRPS: 10,
        concurrency: 1,
        timeout: 5000,
      },
      {
        name: 'openai',
        enabled: true,
        modelName: 'gpt-4o-mini',
        apiKey: 'test-key',
        rateLimitRPS: 10,
        concurrency: 1,
        timeout: 5000,
      },
    ]);

    mockHfProviderCall.mockRejectedValueOnce(new RateLimitError('HF busy', 0.01));
    mockUnifiedProviderCall.mockRejectedValueOnce(new RateLimitError('OpenAI busy', 0.02));

    try {
      await generateReportNow(testInput, 'all-rate-limited-job');
      throw new Error('Expected generateReportNow to throw');
    } catch (error) {
      expect(error).toBeInstanceOf(AllProvidersRateLimitedError);
      const typedError = error as AllProvidersRateLimitedError;
      expect(typedError.retryAfterSeconds).toBe(0.02);
      expect(typedError.providers).toEqual(['hf-space', 'openai']);
      expect(onFailure).toHaveBeenCalledTimes(1);
      expect(onFailure).toHaveBeenCalledWith(
        'all-rate-limited-job',
        expect.arrayContaining([
          expect.objectContaining({ provider: 'hf-space', errorCode: 'RATE_LIMIT' }),
          expect.objectContaining({ provider: 'openai', errorCode: 'RATE_LIMIT' }),
        ]),
        expect.objectContaining({ lastError: 'OpenAI busy' })
      );
    }
  });
});
